repos:
- repo: local #git@github.com:lukegun/mecsim_utils.git
  # Ruff version.
  #rev: v0.14.0
  hooks:
    # Run the linter.
    - id: black
      name: black_linter
      entry: pwd
      args: []
      language: python
